### ISSUE TITLE
Quartz 3 and async

### ISSUE THREAD

**Issue by danielmarbach** [quartznet/quartznet#331]
I'm only starting to dig into the inner workings of Quartz.NET but I already have doubts about the internal design when it comes to scheduling and async. All the things I mention here are not at all a personal critique! Please take no offense. I'm just trying to be helpful and highlight potential problems

Here are a few random thoughts:
- `JobRunShell` is a mixture of blocking and async calls. It should be async only
- I get the intent that the library would like to be backwards compatible. That's why one introduced `IJob`. Since scheduling, persisting, executing jobs, the business logic inside the jobs will likely to touch IO-bound operations I'd suggest to go with a major breaking change and only provide the async version of the job. It is trivial to implement a base class for jobs to remove the crutch of returning a completed task. This removes the unnecessary complexity in the library of handling the sync and the async version and the potential bugs that come with managing two almost distinct code bases.
- The abstractions for the thread pool and the workers do no longer hold up in the async world. The interfaces are built for blocking interactions. I propose to diverge from the java version and introduce new better Task-based abstractions to simplify the code drastically. For example the limiting of concurrency can easily be implemented with `SemaphoreSlim` or if more fanciness is needed with custom task schedulers
- `QuartySchedulerThread`is a weird mixture of async code interacting with the above-mentioned thread pool abstraction and some fancy blocking and non-trivial `Monitor`interaction. `Monitor.Wait`, `ThreadAbortedExceptions`, Pulse etc. belongs to the thread world and should not really be mixed with async code

I'm aware that especially my view on sync vs. async APIs is really provoking. 

If you are interested I'd be willing to help out and see if we can pull quartz .net towards a more but truly async design.
## Plan of Attack
- [x] Make it compile again #335 #338 
- [x] Remove `IAsyncJob` and make `IJob` async #336
- [x] Remove `Async` suffix from methods, see my [reasoning for NServiceBus](https://groups.google.com/forum/#!topic/particularsoftware/xrSJpgjowJQ). I think the same applies here as well.
- [x] Remove interruptable job and replace by cancellation token #339
- [x] Remove blocking calls in `JobRunShell` #345 
- [ ] SimpleThreadPool should become ClrThreadPool (merge Clr to be Simple) informing users about possible no longer supported properties when tried to be set, should use QueuedTaskScheduler to support thread counts and priorities
- TODO

**Comment by roryprimrose** [comment]
Please please please accept this offer from @danielmarbach, he knows his async

**Comment by lahma** [comment]
Contributions are always welcome and would help a lot especially now that I have had so little time give to taking v3 forward. As you have noticed the current solution is hybrid allowing using both the old custom thread pools and async invocation via the standard .NET thread pool - which creates some oddities/ugliness you have described.

Changing to pure Task-based model probably is cleaner even though will require more documentation changes and migration guidance. We should especially keep in mind the current capabilities like maximum thread pool size (concurrent work), locks for DisallowConcurrentExecutionAttribute etc.

If you could introduce changes as reviewable PR chunks that would be great and easier to discuss and hopefully eventually pull in.

**Comment by danielmarbach** [comment]
Ok I will see what I can do. @lahma would it be possible for you to link important things to consider including doco link or a short hint here in this issue so that I don't destroy the core?

**Comment by danielmarbach** [comment]
@lahma have a number of PRs lined up. Will wait until you have a chance to look at it before I produce code which you don't want :dancers:

**Comment by danielmarbach** [comment]
@lahma can we have a chat together? I think I cannot pull of the redesign of the inner scheduling without significantly breaking existin abstractions.

**Comment by lahma** [comment]
@danielmarbach I just created a public Gitter room https://gitter.im/quartznet/quartznet , maybe we can use this? As it might show, I'm been pretty occupied with all other things so apologies for late responses and reactions.

**Comment by danielmarbach** [comment]
No worries. It's not that I'm sitting here and press F5 all day to wait for a response ;) will chime in as soon as I can

**Comment by lahma** [comment]
Alpha 1 has landed to NuGet, please see the [announcement](http://www.quartz-scheduler.net/2016/08/16/quartznet-3.0-alpha1-released.html). So the TODO list should now be shipped. With alpha status we can still move the cheese. Should we close this issue and open new ones for specific work items that come to mind?

**Comment by lahma** [comment]
QuartySchedulerThread is gone, SimpleThreadPool too (DefaultThreadPool is the new kid in town).

**Comment by lahma** [comment]
I'm closing this as most of the async goodness landed in alpha 1, we can open new issues about things that could be further improved.
