### ISSUE TITLE
Quartz.NET 4.0 Roadmap

### ISSUE THREAD

**Issue by lahma** [quartznet/quartznet#988]
This is an umbrella issue gathering things that could be done in 4.0 timeframe.

- [ ] Refactor persistence API to be more document database friendly, https://github.com/quartznet/quartznet/issues/814 probably contributes to this
- [x] Use `ValueTask` instead of `Task`, RamJobStore doesn't need heavy machinery
- [x] Use `Microsoft.Extensions.Logging.Abstractions` instead of liblog
- [x] Add HTTP API for scheduler, maybe via Quartz.AspNetCore package, existing issue #511
- [x] Use the new TimeProvider abstraction #2079
- [x] Remove binary serialization support  #2324
- [x] Remove remoting support #2447
- [x] Remove full framework support #2226

**Comment by Sicos1977** [comment]
A replacement for .net remoting like a rest api would also be a nice thing

**Comment by lahma** [comment]
Thanks @Sicos1977 , added https://github.com/quartznet/quartznet/issues/511 to the list

**Comment by Pinox** [comment]
An option to load persistent data from cloud provider like Azure Table Storage (No SQL) would be an awesome low cost solution for running quartz.  

Currently I have quartz running on seperate SQL DB and it's such a waste of money especially the fact the I'm not running many jobs on the DB.   Table storage where you only pay for the data that you use will make much more sense for many people as I think most Quartz db's are probably very small in size and with something like table storage it's cheap , accessible from anywhere with near infinite scaling.   A 1GB solution on Azure Table Storage will cost you $0.1265 per GB

https://azure.microsoft.com/en-gb/services/storage/tables/

**Comment by lahma** [comment]
@Pinox what I've understood the row key is used for fast lookups in table storage. Quartz needs to check next fire time which is changing value for triggers and if you have thousands of triggers might become a problem. Azure table storage might not scale well in this case?

**Comment by Pinox** [comment]
@lahma   I know there is a limit for transactions (20 000 per second) and entities (2000 per second.) per partition.  So yes if you do more than thousands per second it will not scale well on Azure Table Storage but you still have general NoSQL DB's as option for such scenario's.

I just think if Quartz was able to work on NoSQL then for smaller type workloads it will be a perfect fit for Azure Table Storage and if you really need massive record update per second then you can always throw it in bigger NoSQL DB like CosmoDB / MongoDB or any big DB vendor out there and then you are can use the most appropriate hardware for your task that is persistent and very cost effective.

**Comment by ghd258** [comment]
MYSQL 8.0 now supports JSON format , so you can also run a "NoSQL database" on MYSQL 8.0  without the relational schema that is usually the case.

**Comment by DaveLaa** [comment]
It would be great to have a sepparation of functionality into specific libraries. There could be a Quartz.Net Core dll without external dependencies and specific dlls für the different extensions. This would reduce the necessity to add libraries to a project that doesn't use them.

**Comment by lahma** [comment]
There are some libraries that are ubiquitous, like logging tracing etc so I would consider them as the necessary evil. Especially with .NET Core / NET5 it's quite normal that libraries that need to plug-in into larger constructs have these. DI system is a bit on the fence, but building a bridge is also an option.

**Comment by shatl** [comment]
Please add job execution pipeline to allow applying cross-cutting concerns to job handlers.

Something similar to ASP.NET Core middleware 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-5.0

**Comment by Vandersteen** [comment]
Middleware pipeline would be a welcome addition for us.
I know there are listeners, but they do not allow to 'wrap' things like: https://github.com/quartznet/quartznet/discussions/1224

**Comment by lahma** [comment]
> Middleware pipeline would be a welcome addition for us.
> I know there are listeners, but they do not allow to 'wrap' things like: https://github.com/quartznet/quartznet/discussions/1224

I think a PR would be most welcome. We can start breaking things in main as current version can be branched to 3.x maintenance.

**Comment by Doomer3D** [comment]
Please replace Json.NET with System.Text.Json for .NET 5+

**Comment by mkstephenson** [comment]
I would also second the replacement of Json.NET if it is possible

**Comment by lahma** [comment]
If someone wants to contribute a STJ implementation the same way there's a separate project for NSJ integration, that would be nice. We could offer it in 3.x timeline and make it default in 4.0.

**Comment by mkstephenson** [comment]
I'll have a look at it if I have time, can't promise anything at this stage though.

**Comment by tonyqus** [comment]
> Please replace Json.NET with System.Text.Json for .NET 5+

I don't think  System.Text is mature enough so far. JSON.NET is still much better than System.Text. If you have tried JSON Path Selector feature, you will understand what I mean. Don't replace a library just because the other one is newer.

**Comment by lahma** [comment]
> > Please replace Json.NET with System.Text.Json for .NET 5+
> 
> I don't think System.Text is mature enough so far. JSON.NET is still much better than System.Text. If you have tried JSON Path Selector feature, you will understand what I mean. Don't replace a library just because the other one is newer.

I think we can support both, JSON.NET shouldn't just disappear to ensure existing users keeping the old desired behavior. I can imagine there would be regressions with just changing to STJ, hard to predict things that can go wrong.

**Comment by tonyqus** [comment]
Please consider replacing MS DI with AutoFac. We did see a few unexpected issues happen in MS DI and Scoped lifecycle are not reliable at all. I believe it's kind of design issue of MS DI.

**Comment by tonyqus** [comment]
I'm reading some comparison between Quartz.NET and Hangfire. The major complaint is about how Jobs are created. Hangfire supports any method while Quartz.NET only supports IJob based tasks.

For example,
```
BackgroundJob.Enqueue(
    () => Console.WriteLine("Fire-and-forget!"))
```

I haven't dive deep into the code. Do you think it's possible to support any method with automatic IJob task creation?

**Comment by lahma** [comment]
> Please consider replacing MS DI with AutoFac. We did see a few unexpected issues happen in MS DI and Scoped lifecycle are not reliable at all. I believe it's kind of design issue of MS DI.

Or Lamar, or DryIoc.. the list goes on. There's already an [Autofac integration](https://github.com/alphacloud/Autofac.Extras.Quartz) that you can use. 

> I haven't dive deep into the code. Do you think it's possible to support any method with automatic IJob task creation?

I don't personally like the Hangfire way of things when we start to talk about persisted jobs. Clean and simple for in-memory jobs but complexity starts to hit with things like `() => someService.Method(counter++)`, how to handle all context and captures, makes things harder to test too IMO.

 > Do you think we can add Entity framework based database schema creation feature? If you agree adding this to 4.0, I'm willing to work on that.

I don't think we need EF to just handle schema. Because schema doesn't change that often I think it would be enough to detect via switch whether intitial schema creation is allowed and the schema is missing. Maybe add support for detecting database schema version and if it's different from what Quartz requires, give a startup error.

**Comment by Cricle** [comment]
Will support nosql like `MongoDB`, `LiteDB` store?

**Comment by lahma** [comment]
> Will support nosql like `MongoDB`, `LiteDB` store?
> 
> #1019 I try but there is no suitable one

The core project don't have resources to support such specialized one, you can always improve the existing ones though.

**Comment by Misiu** [comment]
1. Add support for Redis.
There is a project that adds Redis and has a PR that allows support for Quartz 3 (https://github.com/icyice80/QuartzRedisJobStore/pull/4) but official support would be awesome. Especially that the project has some limitations - https://github.com/RedisLabs/redis-quartz#limitations

2. Add documentation and sample on how to configure and use clustering - I have 3 instances of .NET 6 REST API behind Traffic, so I'd like to be able to easily configure clustering in Quartz.

3. Simplify how we register and set up Job Stores. Take a look at https://github.com/glucaci/mongodb-quartz-net#basic-usage, you must set properties (NameValueCollection). Ideally we should be able to do the same using fluent API.

**Comment by Cricle** [comment]
> 1. Add support for Redis.
>    There is a project that adds Redis and has a PR that allows support for Quartz 3 ([Ported to Quartz.net 3 icyice80/QuartzRedisJobStore#4](https://github.com/icyice80/QuartzRedisJobStore/pull/4)) but official support would be awesome. Especially that the project has some limitations - https://github.com/RedisLabs/redis-quartz#limitations
> 2. Add documentation and sample on how to configure and use clustering - I have 3 instances of .NET 6 REST API behind Traffic, so I'd like to be able to easily configure clustering in Quartz.
> 3. Simplify how we register and set up Job Stores. Take a look at https://github.com/glucaci/mongodb-quartz-net#basic-usage, you must set properties (NameValueCollection). Ideally we should be able to do the same using fluent API.

I think `3.` can be a PR(Although the project has been passively updated), if it display or I solved it, I will merge in temp [Nuget package](https://www.nuget.org/packages/MSLog.Quartz.Spi.MongoDbJobStore)

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
> I don't think we need EF to just handle schema. Because schema doesn't change that often I think it would be enough to detect via switch whether intitial schema creation is allowed and the schema is missing. Maybe add support for detecting database schema version and if it's different from what Quartz requires, give a startup error.

Hangfire provides additional nugets to handle schemas with NHibernate.   Yesterday, I started with Quartz.Net because of the issues I was having with Hangfire and Oracle and .Net 6.   After a few hours, it was great that the schema script was available and saved me a great deal of time.   Almost all of the requirements have been handled in just a few hours.  I need to go back and handle load balancing with the AdoJobStore.

**Comment by michaeljon** [comment]
Has anyone done any work getting System.Text.Json as a supported serializer? I'd be willing to pick up and help. We have some really hairy JSON structures and I would not want to have to go back in and write Json.Net serializers for them.

**Comment by mkstephenson** [comment]
I started to look at it and got some stuff down, however I got stuck around some of the structures (and figuring out some of the tests), then some other stuff came up and I didn't get round to finishing it. I just checked the repo now and there appears to be some stuff surrounding System.Text.Json? However I don't know how complete it is.

**Comment by jafin** [comment]
In relation to the DI/container work for 4.0 , there appears work has been done since opening this ticket at improving the stance. Are there still outstanding goals that have not been met?

**Comment by Almaroo** [comment]
Section [How do I chain Job execution? Or, how do I create a workflow?](https://www.quartz-scheduler.net/documentation/faq.html#how-do-i-chain-job-execution-or-how-do-i-create-a-workflow)
mentions that 

> In the future, Quartz will provide a much cleaner way to do this, but until then, you'll have to use one of the above approaches, or think of yet another that works better for you.

Any chances of seeing it in the nearest future?

Cheers

**Comment by lahma** [comment]
> Any chances of seeing it in the nearest future?

Would you be willing to contribute such a feature?

**Comment by Almaroo** [comment]
Provided my design got accepted, sure thing(:

I did not mean to be disrespectful in any way, sorry if it sounded that way(:

**Comment by Khitiara** [comment]
Took a look through documentation for 4.0, it doesnt appear that there's a way to set the logger for quartz from dependency injection - as Microsoft.Extensions.Logging generally injects an ILoggerFactory in the service collection that would be preferred if at all possible (at least for my uses)

**Comment by lahma** [comment]
> Took a look through documentation for 4.0, it doesnt appear that there's a way to set the logger for quartz from dependency injection - as Microsoft.Extensions.Logging generally injects an ILoggerFactory in the service collection that would be preferred if at all possible (at least for my uses)

It's already supported in 3.x series, see the example https://github.com/quartznet/quartznet/tree/3.x/src/Quartz.Examples.AspNetCore and support package https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/microsoft-di-integration.html.

**Comment by Khitiara** [comment]
to clarify my previous statement, I am well aware that injecting the logger from DI is supported in 3.x; the option appears to be missing in 4.x; I was asking if that option is planned to be re-added (the checklist entry for further DI support in this issue does not have an associated more specific issue where i could ask this instead)

**Comment by lahma** [comment]
> to clarify my previous statement, I am well aware that injecting the logger from DI is supported in 3.x; the option appears to be missing in 4.x; I was asking if that option is planned to be re-added (the checklist entry for further DI support in this issue does not have an associated more specific issue where i could ask this instead)

So it's no longer working or what is the problem? There's no plan to remove the support  as far as I know.

**Comment by Khitiara** [comment]
> > to clarify my previous statement, I am well aware that injecting the logger from DI is supported in 3.x; the option appears to be missing in 4.x; I was asking if that option is planned to be re-added (the checklist entry for further DI support in this issue does not have an associated more specific issue where i could ask this instead)
> 
> So it's no longer working or what is the problem? There's no plan to remove the support as far as I know.

on 4.0, there is no way to pull the `ILoggerFactory` from the DI container when setting it up in the `configure` delegate to `AddQuartz` as the only option is to call `SetLoggerFactory` and within that delegate the final `IServiceProvider` is not yet available so only premade `ILoggerFactory` instances are available

**Comment by Khitiara** [comment]
at least as of the current state of the main branch that is

**Comment by lahma** [comment]
> > > to clarify my previous statement, I am well aware that injecting the logger from DI is supported in 3.x; the option appears to be missing in 4.x; I was asking if that option is planned to be re-added (the checklist entry for further DI support in this issue does not have an associated more specific issue where i could ask this instead)
> > 
> > 
> > So it's no longer working or what is the problem? There's no plan to remove the support as far as I know.
> 
> on 4.0, there is no way to pull the `ILoggerFactory` from the DI container when setting it up in the `configure` delegate to `AddQuartz` as the only option is to call `SetLoggerFactory` and within that delegate the final `IServiceProvider` is not yet available so only premade `ILoggerFactory` instances are available

If you can create a public repository showing the problem, that would be nice. Ideally of course a pull request against the main branch fixing the thing as you are quite familiar with the problem domain - it would speed things up a lot.

**Comment by Khitiara** [comment]
https://github.com/Khitiara/Quartz4LoggerInjectionIssue/blob/develop/Program.cs shows a very simplified example of the problem; I would create a pull request but I'm not really sure how to actually solve this issue in an idiomatic way and I'm not intimately familiar with the quartz codebase - I just noticed the issue when trying out the preview out of curiosity

**Comment by SeanFarrow** [comment]
Would adding an EFCore IJobStore implementation be accepted for version 4?
I've already started writing one.

Thanks,
Sean.

**Comment by lahma** [comment]
I've created a PR against `main` (v4 development), which drops support for full framework and makes Quartz require NET 6.0 as minimum target platform: https://github.com/quartznet/quartznet/pull/2226

See poll results: https://github.com/quartznet/quartznet/discussions/2080

**Comment by drieseng** [comment]
@lahma Is **main** now the branch for v4 development? Have all the changes that I implemented on the **v4** branch been merged into **main**?

**Comment by lahma** [comment]
> @lahma Is **main** now the branch for v4 development? Have all the changes that I implemented on the **v4** branch been merged into **main**?

Yes they should all be there,  v4 was merged into main after 3.x was branched from main for maintenance.

**Comment by remcoros** [comment]
@Khitiara you can work around it by doing this:

```cs
var app = await builder.Build();
Quartz.Logging.LogProvider.SetLogProvider(app.Services.GetRequiredService<ILoggerFactory>());
await app.RunAsync();
```

**Comment by Khitiara** [comment]
@remcoros That would work but seems inelegant - thanks for the workaround! I might look into a way to PR support into quartz later for a more elegant solution.

**Comment by izanhzh** [comment]
Looking forward to the release of 4.0, I want HttpApi very much, and I can foresee that the community will easily extend various styles of background management UI

**Comment by candritzky** [comment]
I wish Quartz would support **standard cron expressions** (and have this as a default).
See also #1253.

The current additional syntax options might be nice to have in special cases, but by default or at least with some option, it should adhere to the common standard and e.g. accept "0 0 * * *" as "once every day at midnight".

Currently it demands at least 6 parts (rather than just 5) and it requires either "? * *" or "* * ?" instead of just "* * *" for the last 3 parts.

**Comment by lahma** [comment]
> I wish Quartz would support **standard cron expressions** (and have this as a default).
> See also #1253.
> 
> The current additional syntax options might be nice to have in special cases, but by default or at least with some option, it should adhere to the common standard and e.g. accept "0 0 * * *" as "once every day at midnight".
> 
> Currently it demands at least 6 parts (rather than just 5) and it requires either "? * *" or "* * ?" instead of just "* * *" for the last 3 parts.
> 
> Best way would be to abstract cron expression parsing away and make it replaceable (via DI), so that you can plug in whatever cron expression parser you find best.

So is this a tooling problem where it's inconvenient to have seconds in syntax or unix sysadmins being confused?

**Comment by candritzky** [comment]
@lahma Thanks a lot for getting back so quickly.

It confuses developers, testers, sysadmins and customers. It would be way easier to state that we have a configurable setting that supports **standard cron syntax**. Everyone knows this, can Google this (if needed), and will find tons of examples.

It's way harder to document that that we use cron syntax for configuration, _but_ it's a _little bit_ different. We need to provide all kind of documentation, examples, handle customer support calls, explain why we don't support the standard ("because we decided to go with Quartz.NET...") etc.

It causes overhead and unnecessary brain load - at least as long as you don't need "second granularity" and "year ahead" scheduling.

**Comment by lahma** [comment]
So is there an organization behind this need that would like to pay for the development. or even better, do the development via PR in a backwards compatible way?

**Comment by candritzky** [comment]
@lahma I'll clarify how important this is. Providing a PR could be an option, but I first need to see if I find a way to change this or make this configurable in a backward compatible way.

**Comment by lahma** [comment]
Support for System.Text.Json based JSON serializer has been merged to main and is part of preview packages available from feedz.io feed.

**Comment by panagiotiskompis** [comment]
Is there a target release date for Quartz.Net 4.0?

**Comment by lahma** [comment]
> Is there a target release date for Quartz.Net 4.0?

Nope.

**Comment by panagiotiskompis** [comment]
Thanks for the quick answer!
Two more things please
1) The HTTP API will be released on the Quartz.Net 4.0? I Saw that the checkbox is done in the roadmap
2) Moreover is there a plan for a UI version like the hangfire dashboard?

**Comment by lahma** [comment]
> 1) The HTTP API will be released on the Quartz.Net 4.0? I Saw that the checkbox is done in the roadmap

Yes. There's an example for that in the main branch of the repo.

> 2) Moreover is there a plan for a UI version like the hangfire dashboard?

I'm not aware anyone working on a such thing.

**Comment by lahma** [comment]
I've removed `System.Text.Json` from 4.0 roadmap as it's been backported to 3 and already available in [release 3.10.0](https://github.com/quartznet/quartznet/releases/tag/v3.10.0), 4.0 will change it to be built-in and default.

**Comment by lahma** [comment]
Remoting support (binary RPC calls) was removed from v4 as there is a better HTTP alternative now. If you still need the feature, use 3.x.

**Comment by lahma** [comment]
`main` (v4) now supports only NET 8 (and later).

**Comment by 7amou3** [comment]
Hello, is there a pre-release nuget for this v4?

**Comment by lahma** [comment]
> Hello, is there a pre-release nuget for this v4?

The README points to https://f.feedz.io/quartznet/quartznet/nuget/index.json for preview builds.

**Comment by tomap** [comment]
Hello,

It would be nice to have a pre release version published on nuget.org (my company does not allow stuff outside of nuget.org)
I can use the source code but it's not super convenient

Thank you

**Comment by zhoucm666** [comment]
When will v4.0 be released?

**Comment by Hawxy** [comment]
Would be nice to get v4 out just for the OTEL improvements. OTEL in v3 is unusable at this point due to removed APIs.

**Comment by lahma** [comment]
> Would be nice to get v4 out just for the OTEL improvements. OTEL in v3 is unusable at this point due to removed APIs.

So is there a problem with the contrib libraries that seem to be updated quite often? https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Quartz/1.12.0-beta.1#versions-body-tab

**Comment by Suiram1701** [comment]
> Would be nice to get v4 out just for the OTEL improvements. OTEL in v3 is unusable at this point due to removed APIs.

What exactly do you mean? I'm using 1.11.0-beta.2 of the instrumentation package (there are no differences to the newest version) and everything works fine as implemented.

**Comment by Hawxy** [comment]
Ah, I wasn't aware there was a community instrumentation package, I was referring to the one shipped in v3. Nevermind then.

**Comment by Suiram1701** [comment]
Wouldn't it be an idea to maintain the instrumentation package from here again? I've chatted with one of the maintainers of the otel .net constrib. repo in another topic and he said they try to move away from hosting small instrumentation packages.

**Comment by lahma** [comment]
> Wouldn't it be an idea to maintain the instrumentation package from here again? I've chatted with one of the maintainers of the otel .net constrib. repo in another topic and he said they try to move away from hosting small instrumentation packages.

Yes. It will be built-in without need for extra packages.

**Comment by AdamWyzgol** [comment]
Is there any ETA for 4.0?

**Comment by gimmickj** [comment]
When is Quartz.NET 4.0 expected to be released?

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-alpha.1 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-alpha.1) and the API surface is feature-complete for 4.0.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-alpha.1)** — what 4.0 is, the highlights, and what to check before you start
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — every breaking change with before/after, plus the mandatory schema migration

This is a pre-release: no production use yet, and names can still move on feedback — which is exactly what the alpha is for. Try it against a real application and report what breaks or reads badly. Work queued for the next round is tracked on the [4.0.0-alpha.2 milestone](https://github.com/quartznet/quartznet/milestone/63).

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-alpha.2 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-alpha.2). Alpha.1 was the API becoming complete; alpha.2 is the API being *used* — by the dashboard's own tests, by trimmed builds, by several schedulers in one host — and reshaped where that showed something.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-alpha.2)** — the highlights, the fixes, and what to check before you upgrade from alpha.1 (one schema script to re-run, two listener signatures)
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — every breaking change with before/after, now including the scheduler `Status` enum and the sender-first listener callbacks

What moved, in one paragraph: the scheduler's state is one `Status` value instead of three booleans; every listener callback gets the scheduler it serves; `ConfigureAllQuartzSchedulers` configures every scheduler in a host at once; the dashboard's controls actually work (they did not in alpha.1 — no `_Imports.razor`); a persistent job store survives a trimmed publish; the job-type acquisition filter from #2238 is in, with thanks to @HarnageaGabriel; the scheduler core, the ADO store and the semaphores log through the injected `ILoggerFactory`; and the multi-tenancy pages were rewritten against the code and are now tested against real databases.

Still a pre-release: no production use yet, and names can still move on feedback — say so if `Status`, `SchedulerErrorContext` or `ConfigureAllQuartzSchedulers` reads badly. What is left for 4.0 is tracked on the [4.0 milestone](https://github.com/quartznet/quartznet/milestone/27); the trim/AOT track continues on #3341.

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-alpha.3 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-alpha.3). Alpha.1 was the API becoming complete and alpha.2 the API being *used*; alpha.3 is the release where Quartz is **operated** — a cluster can be read from outside, the persistent store is honest about what it stored and spends a statement on a set rather than on each row, the trimming and native AOT claim is a scheduler that CI publishes natively and runs against a real store, and the test suite proves what the documentation had been promising.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-alpha.3)** — the highlights, the fixes, and what to check before you upgrade from alpha.2 (seven things that stop a build or a start, the lock-handler rename and a registered job taking a scheduler's part by constructor among them; no schema migration this time)
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — every breaking change with before/after, now including `ISemaphore` → `ILockHandler` and the persistent-store builder's renames

What moved, in one paragraph: `IScheduler.QueryClusterNodes()` and a Cluster page say which nodes are alive, overdue or failed, by the same predicate recovery decides with; the dashboard shows the fleet (built or not), execution-group headroom, a trigger-state histogram and node-aware history that forgets by age; every measurement carries `quartz.scheduler.id` and every store emits the same spans through one decorator; a scheduler can be authorized on its own name on the API and the dashboard; every log line in every package has a stable event id; the ADO.NET store is nine files by concern with one failure guard, cluster recovery in named batched steps, a node that was failed out registering itself again, and an acquisition round of `1 + n + 1` statements where it cost `1 + 3n`; the canary publishes natively on three operating systems over a real SQLite store and `Quartz` declares `IsAotCompatible`, with every side package saying whether it can be trimmed; and the DST, misfire, contract, clustering and job-execution suites now run end to end on every dialect that ships — which found and fixed a dozen real defects along the way, among them a job listener that could wedge a firing forever, a dashboard that could fall through to another tenant's scheduler, and a Newtonsoft round trip that silently lost a trigger's time zone (fixed on 3.x as well).

Still a pre-release: no production use yet, and names can still move on feedback — say so if `ILockHandler`, `ConfigureStore` or `AdoJobStoreDependencies` reads badly. What is left for 4.0 is on the [4.0 milestone](https://github.com/quartznet/quartznet/milestone/27), with one decision worth more eyes than mine: #3510, a 30× acquisition win on SQL Server and MySQL that needs a Firebird answer and a sargable lower bound before it can be an index. The trim/AOT track continues on #3341.

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-alpha.4 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-alpha.4). Alpha.1 was the API becoming complete, alpha.2 the API being *used*, alpha.3 the release where Quartz is operated; alpha.4 is the release where Quartz is **integrated** — a framework that embeds it gets an integration surface designed for it, and the proof is a real port: MassTransit's Quartz integration rewritten on these primitives lost 87 lines and two whole classes, replaced three store round trips per upsert with one atomic call, and swapped sixteen stringly-typed `JobDataMap` keys for one typed payload.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-alpha.4)** — the highlights, the corrections its first real integration forced, and what to check coming from alpha.3 (two new trigger columns, the health check's new home, and end times becoming inclusive everywhere)
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — now with a checklist of *silent* behaviour changes: things that compile and behave differently

What moved, in one paragraph: a job can take a typed payload (`IJob<TInput>`) scheduled in one call whose trigger group is a correlation axis, and cancelled by that correlation with one matcher; scheduling inside an `Activity` links the eventual firing back to the request that asked for it, across minutes or days and across nodes; cross-cutting concerns run as `IJobExecutionMiddleware` around the execute call instead of as a wrapper job that breaks `[DisallowConcurrentExecution]`; a trigger carries a first-class, persisted, cluster-safe retry policy — exhaustion returns to the schedule, because one bad hour must not kill a cron trigger; a development store creates its own schema (`ProvisionSchema()`), and `Quartz.Aspire` turns an Aspire connection name into a configured store in one call; a job type rename is one line of configuration; a runnable Wolverine reference example ships in the repo, and two new how-tos write down what every embedder used to reinvent.

Still a pre-release: no production use yet, and names can still move on feedback — the one-off surface just did, corrected by what the MassTransit port asked of it. What is left for 4.0 is on the [4.0 milestone](https://github.com/quartznet/quartznet/milestone/27).

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-alpha.5 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-alpha.5). Alpha.1 was the API becoming complete, alpha.2 the API being *used*, alpha.3 the release where Quartz is operated, alpha.4 where it is integrated; alpha.5 is the release where the API is **finished**. This is the last alpha: breaking changes end here, and the shape you see is the shape 4.0 ships.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-alpha.5)** — cron now says what it means (the wildcard-day footgun, gap-end DST, the rejected forms, the Unix five-field form and `@daily` macros), a job's timeout is middleware, the listener and builder surfaces earn their place, the ADO namespace is a delegate-authoring kit, and acquisition reads at the speed of its index.
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — every removed or renamed member with its replacement, the pre-upgrade cron audit query, and the schema script to re-run.

If something in this shape is wrong for you, now is the moment to say so — beta freezes it.

**Comment by lahma** [comment]
**Quartz.NET 4.0.0-beta.1 is out** — the packages are on [NuGet](https://www.nuget.org/packages/Quartz/4.0.0-beta.1). Alpha.1 was the API becoming complete, alpha.2 the API being *used*, alpha.3 the release where Quartz is operated, alpha.4 where it is integrated, alpha.5 where the API is finished; beta.1 is the release where the API is a **promise**, and the first 4.0 build we ask you to run in production — with its caveats list in hand.

- **[Release notes](https://github.com/quartznet/quartznet/releases/tag/v4.0.0-beta.1)** — what was validated and how, the six corrections taken since alpha.5 (an unauthorized HTTP API or dashboard now refuses to start), the measured numbers, and the caveats.
- **[Migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html)** — now with an ordered upgrade runbook, and a section *Between the alphas and beta.1* for anyone coming from an alpha.
- **[Before You Go Live](https://www.quartz-scheduler.net/documentation/quartz-4.x/production-checklist.html)** — the production checklist, every line a link.

What the beta rests on, in one paragraph: every public member of every shipped package is documented and the compiler holds it there; 336 documented behaviours were mapped to the test that asserts each and the gaps were pinned; the 3.20 → 4.0 upgrade is rehearsed in CI on every dialect against rows a released 3.20 wrote; two clustered nodes ran a mixed workload for thirty minutes on PostgreSQL and on SQL Server with zero overlaps and nothing left behind; a firing on a persistent store is 1.5× faster and allocates 2.4× less than on 3.20, and on the in-memory store it is faster than 3.20 too; and the extension seams are registered, with the rule that any member added to a public interface arrives as a default one.

From here to 4.0: additive changes only. If a caveat on the list is the one that stops you, say so here — that is what the list is for.

**Comment by lahma** [comment]
**4.0.0-rc.1 is on NuGet** — the release candidate. **4.0.0 is this commit**, tagged when the last hand-run gates are green and no later than a week from now; only the release notes and the site change between the two, unless a blocker forces an rc.2.

Release notes: https://github.com/quartznet/quartznet/releases/tag/v4.0.0-rc.1

What it is, in one paragraph: the packages, the docs and the upgrade path were exercised as a user meets them — every documented journey built from scratch against the published beta.1, every example started, a security review of the HTTP API, the dashboard and the client, a stable-version pack, a **running** 3.20 cluster upgraded by the runbook through its mixed-version window on PostgreSQL and SQL Server, and a clustered soak. What they found is fixed in this build: one cross-tenant read on the dashboard under per-scheduler authorization, a job type named over the wire being resolved on receipt, `IgnoreDuplicates` on its own being a startup error, `SendMailJob` handing a container credential to a job-data host, a paused job group not binding later jobs on the persistent store, and a 3.x schema that could start and fire nothing. One deliberate shape change against the beta.1 freeze — two dashboard DTO flags are `bool?` — is called out in the notes with its reason.

If you ran beta.1: run `schema_30_to_40_indexes_<database>.sql` once the last 3.x node is gone (the index section is its own file now), and read the notes' "If you ran beta.1" list. Coming from 3.x: the migration guide now reads as one document, with a *Start here* at the top.

```shell
dotnet add package Quartz --version 4.0.0-rc.1
```

**Comment by lahma** [comment]
**4.0.0-rc.2 is on NuGet.** rc.1 was upgraded to by a real application running 3.19.1 in production, and that upgrade found three things the gates had not: a process without the job classes could not reschedule (#3705), stopping the host twice at once threw out of `RunAsync` (#3701), and an expression written for another six-field cron dialect now parses where 3.x refused it, with two shapes firing on a different day (#3706, documented with an audit). All three are in rc.2; the API, the schema and the dependencies are rc.1's. Notes: https://github.com/quartznet/quartznet/releases/tag/v4.0.0-rc.2

**4.0.0 is this commit** once the same production upgrade is repeated against it and comes back clean.

```shell
dotnet add package Quartz --version 4.0.0-rc.2
```

**Comment by lahma** [comment]
**Quartz.NET 4.0.0 is released.** https://github.com/quartznet/quartznet/releases/tag/v4.0.0 — the notes there are the short form; the [migration guide](https://www.quartz-scheduler.net/documentation/quartz-4.x/migration-guide.html) is the long one, and the [4.0 post](https://www.quartz-scheduler.net/blog.html) says what it is.

```shell
dotnet add package Quartz
```

This roadmap opened in 2020 and closes with the release. Of what it asked for: `net10.0` only, a container-built scheduler with dependency injection and hosting in the core package, `ValueTask` and cancellation throughout, the HTTP API and the dashboard, recurrence triggers, the paged queries, `TriggerState.Executing`, a retry policy, typed job input, OpenTelemetry through a named source and meter, and a trimmed public surface. The one item that did not make 4.0 is the document-database-friendly persistence API, which is tracked as #3687 on the 4.1 milestone — `UseJobStore<T>` is the seam it will use.

Thank you to everyone who commented here over the years it stayed open, and to everyone who ran a pre-release and said what broke.
